#config_version=6

mode:
  priority: 500
  start_events: game_ending, start_high_score
  use_wait_queue: true

high_score:
  _overwrite: true
  enter_initials_timeout: 0
  # define your high score categories and the awards
  categories: !!omap
    - score:
        - GRAND CHAMPION
  defaults:
    score:
      - AAA: 80000