#config_version=6

mode:
  start_events: mode_base_started
  priority: 100
  events_when_started: craters_setup

event_player:
  craters_setup:
    continue_craters
  crater_1_hit:
    temp_freeze_craters
  crater_2_hit:
    temp_freeze_craters
  crater_3_hit:
    temp_freeze_craters
  crater_4_hit:
    temp_freeze_craters
  freeze_hit:
    - freeze_craters
    - show_frozen_craters|100ms
  craters_freeze_hit:
    - freeze_craters
    - show_frozen_craters|100ms
    - continue_craters|2s
  temp_freeze_craters:
    continue_craters|1s
  playfield_active:
    continue_craters|1s

timers:
  craters_timer:
    start_value: 0
    end_value: 5
    tick_interval: 200ms
    direction: up
    control_events:
      - action: start
        event: continue_craters
      - action: stop
        event: temp_freeze_craters
      - action: stop
        event: freeze_craters
    restart_on_complete: true

shot_profiles:
  crater_shot_profile:
    advance_on_hit: false
    states:
      - name: unlit
      - name: lit

shots:
  craters_freeze:
    switch: s_freeze
    mark_playfield_active: false
    enable_events: playfield_active
    disable_events: craters_setup
  crater_1:
    switch: s_crater_1
    profile: crater_shot_profile
  crater_2:
    switch: s_crater_2
    profile: crater_shot_profile
  crater_3:
    switch: s_crater_3
    profile: crater_shot_profile
  crater_4:
    switch: s_crater_4
    profile: crater_shot_profile

variable_player:
  crater_1_hit:
    score: 1000 * current_player.playfield_multiplier
    crater_1_scored:
      int: 1
      action: set
  crater_2_hit:
    score: 4000 * current_player.playfield_multiplier
    crater_2_scored:
      int: 1
      action: set
  crater_3_hit:
    score: 9000 * current_player.playfield_multiplier
    crater_3_scored:
      int: 1
      action: set
  crater_4_hit:
    score: 16000 * current_player.playfield_multiplier
    crater_4_scored:
      int: 1
      action: set
  timer_craters_timer_tick{ticks==0}:
    craters_freeze_index:
      int: 1
      action: set
  timer_craters_timer_tick{ticks==1}:
    craters_freeze_index:
      int: 2
      action: set
  timer_craters_timer_tick{ticks==2}:
    craters_freeze_index:
      int: 3
      action: set
  timer_craters_timer_tick{ticks==3}:
    craters_freeze_index:
      int: 4
      action: set

show_player:
  timer_craters_timer_tick{ticks==0}:
    crater_4:
      loops: 1
  timer_craters_timer_tick{ticks==1}:
    crater_3:
      loops: 1
  timer_craters_timer_tick{ticks==2}:
    crater_2:
      loops: 1
  timer_craters_timer_tick{ticks==3}:
    crater_1:
      loops: 1
  timer_craters_timer_tick{ticks==4}:
    craters_off:
      loops: 1
  crater_1_hit:
    crater_1_hit_show:
      loops: 1
  crater_2_hit:
    crater_2_hit_show:
      loops: 1
  crater_3_hit:
    crater_3_hit_show:
      loops: 1
  crater_4_hit:
    crater_4_hit_show:
      loops: 1
  show_frozen_craters{current_player.craters_freeze_index==1}:
    crater_4:
      loops: -1
      priority: 500
  show_frozen_craters{current_player.craters_freeze_index==2}:
    crater_3:
      loops: -1
      priority: 500
  show_frozen_craters{current_player.craters_freeze_index==3}:
    crater_2:
      loops: -1
      priority: 500
  show_frozen_craters{current_player.craters_freeze_index==4}:
    crater_1:
      loops: -1
      priority: 500
  continue_craters:
    crater_1:
      action: stop
    crater_2:
      action: stop
    crater_3:
      action: stop
    crater_4:
      action: stop
    crater_1_hit_show:
      action: stop
    craters_off:
      action: stop

shows:
  crater_1:
    - duration: 150ms
      lights:
        l_crater_1: white
        l_crater_2: white
        l_crater_3: white
        l_crater_4: white
  crater_2:
    - duration: 150ms
      lights:
        l_crater_2: white
        l_crater_3: white
        l_crater_4: white
  crater_3:
    - duration: 150ms
      lights:
        l_crater_3: white
        l_crater_4: white
  crater_4:
    - duration: 150ms
      lights:
        l_crater_4: white
  crater_1_hit_show:
    - duration: 150ms
      lights:
        l_crater_1: white
    - duration: 150ms
      lights:
        l_crater_1: off
    - duration: 150ms
      lights:
        l_crater_1: white
    - duration: 150ms
      lights:
        l_crater_1: off
  crater_2_hit_show:
    - duration: 150ms
      lights:
        l_crater_2: white
    - duration: 150ms
      lights:
        l_crater_2: off
    - duration: 150ms
      lights:
        l_crater_2: white
    - duration: 150ms
      lights:
        l_crater_2: off
  crater_3_hit_show:
    - duration: 150ms
      lights:
        l_crater_3: white
    - duration: 150ms
      lights:
        l_crater_3: off
    - duration: 150ms
      lights:
        l_crater_3: white
    - duration: 150ms
      lights:
        l_crater_3: off
  crater_4_hit_show:
    - duration: 150ms
      lights:
        l_crater_4: white
    - duration: 150ms
      lights:
        l_crater_4: off
    - duration: 150ms
      lights:
        l_crater_4: white
    - duration: 150ms
      lights:
        l_crater_4: off
  craters_off:
    - duration: 150ms
      lights:
        l_crater_1: off
        l_crater_2: off
        l_crater_3: off
        l_crater_4: off