#config_version=6

mode:
  start_events: ball_started
  priority: 100
  events_when_started: base_setup

variable_player:
  10pt_standing_hit:
    score: 10 * current_player.playfield_multiplier
  player_bonus_val_tmp{change > 0 and current_player.bonus_val + change > 19}:
    bonus_val:
      int: 19
      action: set
  player_bonus_val_tmp{change > 0 and current_player.bonus_val + change <= 19}:
    bonus_val:
      int: current_player.bonus_val + change
      action: set
  single_player_ball_started:
    bonus_val_tmp: 1
  rollunder_hit:
    bonus_val_tmp: 1
    score: 3000 * current_player.playfield_multiplier
  kicker_hit{settings.balls_per_game==3}:
    score: 1000
  kicker_hit{settings.balls_per_game==5}:
    score: 100

shots:
  10pt_standing:
    switch: s_10pt_top, s_10pt_left_targets, s_10pt_right_targets, s_10pt_left_upper, s_10pt_left_mid
  freeze:
    switch: s_freeze
    mark_playfield_active: false
    disable_events: playfield_active
  rollunder:
    switch: s_rollunder
  kicker:
    switch: s_kicking_target