#config_version=6

mode:
  start_events: ball_started
  priority: 100

#slide_player:
#  mode_base_started:
#    widgets:
#      - type: text
#        text: (score)
#        number_grouping: true
#        min_digits: 2
#        font_size: 100
#      - type: text
#        text: PLAYER (number)
#        y: 10
#        x: 10
#        font_size: 50
#        anchor_x: left
#        anchor_y: bottom
#      - type: text
#        text: BALL (ball)
#        y: 10
#        x: right-10
#        anchor_x: right
#        anchor_y: bottom
#        font_size: 50
##! test
#! start_game
#! assert_mode_running base
#! assert_text_on_top_slide "00"
#! assert_text_on_top_slide "PLAYER 1"
#! assert_text_on_top_slide "BALL 1"

#shots:
#  shot_outlane:
#    switch: s_rollover_left_outlane, s_rollover_right_outlane
#
#variable_player:
#  shot_outlane_hit:
#    score: 1000
