#config_version=6
mode:
  start_events: mode_base_started
  priority: 100
  events_when_started: firepit_setup

ball_holds:
  firepit:
    balls_to_hold: 1
    hold_devices: bd_firepit
    enable_events: firepit_setup
    release_one_events: timer_firepit_timer_complete

timers:
  firepit_timer:
    start_value: 0
    end_value: 1
    tick_interval: 1s
    direction: up
    control_events:
      - action: start
        event: balldevice_bd_firepit_ball_entered
      - action: reset
        event: balldevice_bd_firepit_ejecting_ball
    restart_on_complete: false

variable_player:
  firepit_hit:
    score: 5000 * current_player.playfield_multiplier
  firepit_hit{current_player.extra_ball_ready==1 and settings.novelty_mode==1}:
    score: 50000 * current_player.playfield_multiplier
    extra_ball_ready:
      int: 0
      action: set
  firepit_hit{current_player.outlane_eb_ready==1 and settings.novelty_mode==1}:
    score: 50000 * current_player.playfield_multiplier
    outlane_eb_ready:
      int: 0
      action: set
  award_extra_ball:
    extra_ball_ready:
      int: 0
      action: set
  outlane_eb_ready:
    outlane_eb_ready:
      int: 1
      action: set
  outlane2eb_hit:
    outlane_eb_ready:
      int: 0
      action: set

event_player:
  firepit_hit{current_player.extra_ball_ready==1 and settings.novelty_mode==0}:
    award_extra_ball
  player_extra_ball_ready{value==1}:
    extra_ball_ready
  firepit_hit{current_player.outlane_eb_ready==1 and settings.novelty_mode==0}:
    award_outlane_extra_ball

shots:
  firepit:
    switch: s_firepit_kicker

shows:
  eb_ready:
    - duration: 150ms
      lights:
        l_extra_ball: on

show_player:
  extra_ball_extra_ball_lit:
    eb_ready:
      loops: -1
  award_extra_ball:
    eb_ready:
      action: stop
  firepit_hit{current_player.extra_ball_ready==1 and settings.novelty_mode==1}:
    eb_ready:
      action: stop
  extra_ball_outlane_extra_ball_lit:
    eb_ready:
      loops: -1
  award_outlane_extra_ball:
    eb_ready:
      action: stop
  firepit_hit{current_player.outlane_eb_ready==1 and settings.novelty_mode==1}:
    eb_ready:
      action: stop
  #The following comes from the outlanetoextraball.yaml file.
  outlane2eb_hit:
    eb_ready:
      action: stop