#config_version=6

# This mode responds to events from other modes -
#
# stop_tunnel_value, start_tunnel_value, collect_tunnel_value

mode:
  start_events: ball_started
  priority: 100
  events_when_started: tunnel_mode_start

state_machines:
  tunnel_state_machine:
    states:
      level_1000:
        label: 1000pts
        events_when_started: tunnel_point_1000
      level_2000:
        label: 2000pts
        events_when_started: tunnel_point_2000
      level_3000:
        label: 3000pts
        events_when_started: tunnel_point_3000
      level_4000:
        label: 4000pts
        events_when_started: tunnel_point_4000
      start:
        label: 5000pts
        events_when_started: tunnel_point_5000
    transitions:
      - source: level_1000
        target: level_2000
        events: timer_tunnel_timer_tick
      - source: level_2000
        target: level_3000
        events: timer_tunnel_timer_tick
      - source: level_3000
        target: level_4000
        events: timer_tunnel_timer_tick
      - source: level_4000
        target: start
        events: timer_tunnel_timer_tick
      - source: start
        target: level_1000
        events: timer_tunnel_timer_tick

timers:
  tunnel_timer:
    restart_on_complete: true
    control_events:
      - event: start_tunnel_value
        action: start
      - event: stop_tunnel_value
        action: pause

event_player:
  tunnel_mode_start:
    - start_tunnel_value
#  stop_tunnel_value:
#    - nothing
#  start_tunnel_value:
#    - nothing
#  collect_tunnel_value:
#    - nothing

show_player:
  tunnel_mode_start:
    tunnel_cycle:
      show_tokens:
        light_on: l_tunnel_1000
        light_off: l_tunnel_5000
  tunnel_point_1000:
    tunnel_cycle:
      show_tokens:
        light_on: l_tunnel_1000
        light_off: l_tunnel_5000
  tunnel_point_2000:
    tunnel_cycle:
      show_tokens:
        light_on: l_tunnel_2000
        light_off: l_tunnel_1000
  tunnel_point_3000:
    tunnel_cycle:
      show_tokens:
        light_on: l_tunnel_3000
        light_off: l_tunnel_2000
  tunnel_point_4000:
    tunnel_cycle:
      show_tokens:
        light_on: l_tunnel_4000
        light_off: l_tunnel_3000
  tunnel_point_5000:
    tunnel_cycle:
      show_tokens:
        light_on: l_tunnel_5000
        light_off: l_tunnel_4000

variable_player:
  tunnel_point_1000:
    tunnel_score:
      int: 1000
      action: set
  tunnel_point_2000:
    tunnel_score:
      int: 2000
      action: set
  tunnel_point_3000:
    tunnel_score:
      int: 3000
      action: set
  tunnel_point_4000:
    tunnel_score:
      int: 4000
      action: set
  tunnel_point_5000:
    tunnel_score:
      int: 5000
      action: set
  collect_tunnel_value:
    score: current_player.tunnel_score