#config_version=6

mode:
  start_events: ball_started
  priority: 100

shots:
  target_100:
    switch: s_target_100
  target_extra_ball:
    switch: s_target_extra_ball
  rollover_stop_tunnel:
    switch: s_rollover_stop_tunnel
  rollover_collect_tunnel:
    switch: s_rollover_center_top
  target_start_tunnel:
    switch: s_target_left_start_tunnel, s_target_right_start_tunnel
  target_collect_and_up_post:
    switch: s_target_center_collect_tunnel
  downpost_rollovered:
    switch: s_downpost_left, s_downpost_right
  rollover_outlane:
    switch: s_rollover_left_outlane, s_rollover_right_outlane

variable_player:
  target_100_hit:
    score: 100
  target_start_tunnel_hit:
    score: 100
  rollover_outlane_hit:
    score: 1000

event_player:
  target_extra_ball_hit:
    - do_check_extra_ball
  rollover_stop_tunnel_hit:
    - stop_tunnel_value
  rollover_collect_tunnel_hit:
    - collect_tunnel_value
  target_start_tunnel_hit:
    - start_tunnel_value
  target_collect_and_up_post_hit:
    - collect_tunnel_value
    - apply_up_post
  downpost_rollovered_hit:
    - apply_down_post

#TODO
# Apply do_check_extra_ball, stop_tunnel_value, collect_tunnel_value, start_tunnel_value, apply_up_post, apply_down_post