#config_version=6

mode:
  start_events: ball_started
  priority: 100

shots:
  shot_saucers:
    switch: s_saucer_left, s_saucer_right
  shot_saucer_left:
    switch: s_saucer_left
  shot_saucer_right:
    switch: s_saucer_right
  shot_gate_thru_path:
    switch: s_rollover_gates_top_a, s_rollover_gates_top_b, s_rollover_gates_bottom_a, s_rollover_gates_bottom_b
  shot_gate_collect_tunnel:
    switch: s_rollover_gates_bottom_b

variable_player:
    shot_saucers_hit:
      score: 500
    shot_gate_thru_path_hit:
      score: 1000

event_player:
    shot_saucer_left_hit:
      - launch_gate_open_lower
    shot_saucer_right_hit:
      - launch_gate_open_upper
    shot_gate_collect_tunnel_hit:
      - collect_tunnel_value

#TODO Handle the launch_gate_open_lower and launch_gate_open_upper, and collect_tunnel_value events
