#config_version=6

coils:
  c_flipper_left_power:
    number:
    allow_enable: true
    default_pulse_ms: 20
  c_flipper_left_hold:
    number:
    allow_enable: true
    default_pulse_ms: 20
  c_flipper_right_power:
    number:
    allow_enable: true
    default_pulse_ms: 20
  c_flipper_right_hold:
    number:
    allow_enable: true
    default_pulse_ms: 20
  c_drain_eject:
    number: 2
    default_pulse_ms: 20
  c_trough_release:
    number:
  c_pop_upper:
    number: 5
  c_pop_mid:
    number: 6
  c_pop_lower_left:
    number: 7
  c_pop_lower_right:
    number: 8
  c_slingshot_left:
    number: 10
  c_slingshot_right:
    number: 11
  c_subway_eject:
    number:

autofire_coils:
  slingshot_left:
    coil: c_slingshot_left
    switch: s_slingshot_left
  slingshot_right:
    coil: c_slingshot_right
    switch: s_slingshot_right
  pop_upper:
    coil: c_pop_upper
    switch: s_pop_upper
  pop_mid:
    coil: c_pop_mid
    switch: s_pop_mid
  pop_lower_left:
    coil: c_pop_lower_left
    switch: s_pop_lower_left
  pop_lower_right:
    coil: c_pop_lower_right
    switch: s_pop_lower_right

flippers:
  flipper_left:
    main_coil: c_flipper_left_power
    hold_coil: c_flipper_left_hold
    activation_switch: s_flipper_left
    eos_switch: s_flipper_left_eos
    repulse_on_eos_open: true
  flipper_right:
    main_coil: c_flipper_right_power
    hold_coil: c_flipper_right_hold
    activation_switch: s_flipper_right
    eos_switch: s_flipper_right_eos
    repulse_on_eos_open: true