#config_version=6

config:
  - assets.yaml
  - coils.yaml
  - displays.yaml
  - hardware.yaml
  - keyboard.yaml
  - lights.yaml
  - slides.yaml
  - switches.yaml
  - widgets.yaml

modes:
# base modules
  - base
  - tilt
# game logic
  - gates
  - pops
  - bumpers
  - fixed
  - listener
  - kicker
  - tunnel

slide_player:
  init_done: screen_segement_display

widget_player:
  init_done:
    backglass:
      slide: screen_segement_display
    display1:
      slide: screen_segement_display
    display2:
      slide: screen_segement_display
    display3:
      slide: screen_segement_display
    display4:
      slide: screen_segement_display
    display5:
      slide: screen_segement_display
