#config_version=6

config:
  - assets.yaml
  - coils.yaml
  - balldevices.yaml
  - displays.yaml
  - hardware.yaml
  - keyboard.yaml
  - lights.yaml
  - switches.yaml
  - widgetstyles.yaml
  - segmentdisplays.yaml
  - credits.yaml
  - sound.yaml
  - settings.yaml
  - variables.yaml
  - droptargets.yaml

modes:
# base modules
  - base
  - game
  - tilt
  - displays
  - service
  - service_dmd
  - credits
  - high_score
  - bonus
  - match
  - tilt
# game logic
  - basepops
  - multiball
  - basedrops
  - backboxplumes
  - basecraters
  - basefirepit
  - basesaucer
  - basespinner
  - baselanesandgate
  - baseballsave

custom_code:
  - custom_code.bonus_counter.BonusCounter
  - custom_code.bonus_light_controller.BonusLightController
  - custom_code.drain_to_extra_ball.DrainToExtraBall
  - custom_code.match_alerter.MatchAlerter

game:
  balls_per_game: settings.balls_per_game
  max_players: 4