#config_version=6

config:
  - assets.yaml
  - coils.yaml
  - displays.yaml
  - hardware.yaml
  - keyboard.yaml
  - lights.yaml
  - slides.yaml
  - switches.yaml
  - widgetstyles.yaml
  - segmentdisplays.yaml

modes:
# base modules
  - base
  - game
  - tilt
  - displays
# game logic
  #- gates
  #- pops
  #- bumpers
  #- fixed
  #- listener
  #- kicker
  #- tunnel


