#config_version=6

config:
  - assets.yaml
  - coils.yaml
  - balldevices.yaml
  - displays.yaml
  - hardware.yaml
  - keyboard.yaml
  - lights.yaml
  - switches.yaml
  - widgetstyles.yaml
  - segmentdisplays.yaml
  - credits.yaml
  - sound.yaml
  - settings.yaml
  - variables.yaml
  - droptargets.yaml

modes:
# base modules
  - base
  - game
  - tilt
  - displays
  - service
  - service_dmd
  - credits
  - high_score
# game logic
  - pops
  - multiball
  - basedrops

game:
  balls_per_game: settings.balls_per_game
  max_players: 4