#config_version=6

config:
  - assets.yaml
  - coils.yaml
  - displays.yaml
  - hardware.yaml
  - keyboard.yaml
  - lights.yaml
  - switches.yaml
  - widgetstyles.yaml
  - segmentdisplays.yaml
  - credits.yaml
  - sound.yaml

modes:
# base modules
  - base
  - game
  - tilt
  - displays
  - service
  - service_dmd
  - credits
# game logic
  - pops