#config_version=6

displays:
  window:
    width: 800
    height: 480
    default: true

window:
  width: 800
  height: 480
  title: Volcano
  resizable: true
  borderless: false
  fullscreen: false
  exit_on_escape: true
  source_display: window