#config_version=6

hardware:
  platform: opp
  driverboards: gen2

psus:
  default:
    #Gives the capacitors extra time to recharge after firing a coil
    #  and eases the load on the power supply. Doesn't affect autofire
    #  devices like flippers, pops, slings.
    release_wait_ms: 50

playfields:
  playfield:
    tags: default
    default_source_device: bd_drain

flippers:
  left_flipper:
    main_coil: c_flipper_left
    activation_switch: s_left_flipper
  right_flipper:
    main_coil: c_flipper_right
    activation_switch: s_right_flipper

virtual_platform_start_active_switches: s_drain

window:
  width: 800
  height: 480
  title: Volcano
  resizable: false
  borderless: true
  fullscreen: false
  exit_on_escape: true
  source_display: window