#config_version=6
hardware:
  segment_displays: light_segment_displays

segment_displays:
  display1:
    size: 6
    number: 1
    default_transition_update_hz: 24
  display2:
    size: 6
    number: 1
    default_transition_update_hz: 24
  display3:
    size: 6
    number: 1
    default_transition_update_hz: 24
  display4:
    size: 6
    number: 1
    default_transition_update_hz: 24
  display5:
    size: 4
    number: 1
    default_transition_update_hz: 24

# The remainder of this file sets up the screen display version of segment displays w/ backglass
virtual_segment_display_connector:
  segment_displays: display1, display2, display3, display4, display5

widgets:
  backglass:
    - type: image
      image: VolcanoBackglass
      z: 1
  display1:
    - type: segment_display_emulator
      name: display1
      display_type: 7seg
      character_count: 6
      padding: 0
      character_spacing: 10
      segment_width: 0.1
      segment_interval: .02
      segment_off_color: ffffffff
      segment_on_color: 000000ff
      side_bevel_enabled: false
      background_color: ffffffff
      dot_enabled: false
      comma_enabled: false
      text: "888888"
      width: 130
      height: 22
      x: 194
      y: 453
      z: 200
  display2:
    - type: segment_display_emulator
      name: display2
      display_type: 7seg
      character_count: 6
      padding: 0
      character_spacing: 10
      segment_width: 0.1
      segment_interval: .02
      segment_off_color: ffffffff
      segment_on_color: 000000ff
      side_bevel_enabled: false
      background_color: ffffffff
      dot_enabled: false
      comma_enabled: false
      text: "888888"
      width: 130
      height: 22
      x: 605
      y: 453
      z: 200
  display3:
    - type: segment_display_emulator
      name: display3
      display_type: 7seg
      character_count: 6
      padding: 0
      character_spacing: 10
      segment_width: 0.1
      segment_interval: .02
      segment_off_color: ffffffff
      segment_on_color: 000000ff
      side_bevel_enabled: false
      background_color: ffffffff
      dot_enabled: false
      comma_enabled: false
      text: "888888"
      width: 130
      height: 22
      x: 194
      y: 325
      z: 200
  display4:
    - type: segment_display_emulator
      name: display4
      display_type: 7seg
      character_count: 6
      padding: 0
      character_spacing: 10
      segment_width: 0.1
      segment_interval: .02
      segment_off_color: ffffffff
      segment_on_color: 000000ff
      side_bevel_enabled: false
      background_color: ffffffff
      dot_enabled: false
      comma_enabled: false
      text: "888888"
      width: 130
      height: 22
      x: 605
      y: 325
      z: 200
  display5:
    - type: segment_display_emulator
      name: display5
      display_type: 7seg
      character_count: 4
      padding: 0
      character_spacing: 7
      segment_width: 0.1
      segment_interval: .02
      segment_off_color: ffffffff
      segment_on_color: 000000ff
      side_bevel_enabled: false
      background_color: ffffffff
      dot_enabled: false
      comma_enabled: false
      text: "8888"
      width: 68
      height: 22
      x: 400
      y: 183
      z: 200

slides:
  screen_segement_display: []

slide_player:
  displays_init_done: screen_segement_display

widget_player:
  displays_init_done:
    backglass:
      slide: screen_segement_display
      priority: 10
    display1:
      slide: screen_segement_display
      priority: 10
    display2:
      slide: screen_segement_display
      priority: 10
    display3:
      slide: screen_segement_display
      priority: 10
    display4:
      slide: screen_segement_display
      priority: 10
    display5:
      slide: screen_segement_display
      priority: 10