#config_version=6

switches:
  s_coin_left:
    number:
  s_coin_center:
    number:
  s_coin_right:
    number:
  s_pop_upper:
    number:
  s_pop_mid:
    number:
  s_pop_lower_left:
    number:
  s_pop_lower_right:
    number:
  s_slingshot_left:
    number:
  s_slingshot_right:
    number:
  s_flipper_left:
    number:
    tags: left_flipper
  s_flipper_left_eos:
    number:
  s_flipper_right:
    number:
    tags: right_flipper
  s_flipper_right_eos:
    number:
  s_flipper_right_upper_eos:
    number:
  s_drain:
    number:
  s_trough_left:
    number:
  s_trough_right:
    number:
  s_plunger:
    number:
  s_start:
    number:
    tags: start
  s_service_enter:
    number:
    tags: service_enter
  s_service_esc:
    number:
    tags: service_esc
  s_service_up:
    number:
    tags: service_up
  s_service_down:
    number:
    tags: service_down
  s_subway_1:
    number:
  s_subway_2:
    number:
  s_subway_3:
    number:
  s_firepit_kicker:
    number:
  s_spinner:
    number:
    tags: playfield_active
  s_top_saucer:
    number:
  s_kicking_target:
    number:
  s_left_targets_1:
    number:
  s_left_targets_2:
    number:
  s_left_targets_3:
    number:
  s_left_targets_4:
    number:
  s_left_targets_5:
    number:
  s_right_targets_1:
    number:
  s_right_targets_2:
    number:
  s_right_targets_3:
    number:
  s_right_targets_4:
    number:
  s_right_targets_5:
    number:
  s_crater_1:
    number:
    tags: playfield_active
  s_crater_2:
    number:
    tags: playfield_active
  s_crater_3:
    number:
    tags: playfield_active
  s_crater_4:
    number:
    tags: playfield_active
  s_10pt_top:
    number:
    tags: playfield_active
  s_10pt_left_targets:
    number:
    tags: playfield_active
  s_10pt_right_targets:
    number:
    tags: playfield_active
  s_10pt_left_upper:
    number:
    tags: playfield_active
  s_10pt_left_mid:
    number:
    tags: playfield_active
  s_spot_target:
    number:
    tags: playfield_active
  s_outlane_right:
    number:
    tags: playfield_active
  s_outlane_left:
    number:
    tags: playfield_active
  s_return_left:
    number:
    tags: playfield_active
  s_rollunder:
    number:
    tags: playfield_active
  s_freeze:
    number: