#config_version=6

switches:
  s_coin_left:
    number:
  s_coin_center:
    number:
  s_coin_right:
    number:
  s_pop_upper:
    number:
  s_pop_mid:
    number:
  s_pop_lower_left:
    number:
  s_pop_lower_right:
    number:
  s_slingshot_left:
    number:
  s_slingshot_right:
    number:
  s_flipper_left:
    number:
    tags: left_flipper
  s_flipper_left_eos:
    number:
  s_flipper_right:
    number:
    tags: right_flipper
  s_flipper_right_eos:
    number:
  s_drain:
    number:
  s_trough_left:
    number:
  s_trough_right:
    number:
  s_plunger:
    number:
  s_start:
    number:
    tags: start
  s_service_enter:
    number:
    tags: service_enter
  s_service_esc:
    number:
    tags: service_esc
  s_service_up:
    number:
    tags: service_up
  s_service_down:
    number:
    tags: service_down
  s_subway_1:
    number:
  s_subway_2:
    number:
  s_subway_3:
    number: