#config_version=6

# Screen display version of segment displays & backglass

widgets:
  backglass:
    - type: image
      image: SpaceTimeBackglass
      z: 10

  display1:
    - type: segment_display_emulator
      name: display1
      character_count: 7
      character_slant_angle: 5
      character_spacing: 5
      segment_width: 0.1
      segment_interval: .02
      segment_off_color: 4b4c4a30
      segment_on_color: ffa500ff
      side_bevel_enabled: true
      dot_enabled: true
      comma_enabled: true
      text: ""
      width: 135
      height: 60
      x: 245
      y: 347
      z: 2

  display2:
    - type: segment_display_emulator
      name: display2
      character_count: 7
      character_slant_angle: 5
      character_spacing: 5
      segment_width: 0.1
      segment_interval: .02
      segment_off_color: 4b4c4a30
      segment_on_color: ffa500ff
      side_bevel_enabled: true
      dot_enabled: true
      comma_enabled: true
      text: ""
      width: 135
      height: 60
      x: 555
      y: 347
      z: 2

  display3:
    - type: segment_display_emulator
      name: display3
      character_count: 7
      character_slant_angle: 5
      character_spacing: 5
      segment_width: 0.1
      segment_interval: .02
      segment_off_color: 4b4c4a30
      segment_on_color: ffa500ff
      side_bevel_enabled: true
      dot_enabled: true
      comma_enabled: true
      text: ""
      width: 135
      height: 60
      x: 245
      y: 97
      z: 2

  display4:
    - type: segment_display_emulator
      name: display4
      character_count: 7
      character_slant_angle: 5
      character_spacing: 5
      segment_width: 0.1
      segment_interval: .02
      segment_off_color: 4b4c4a30
      segment_on_color: ffa500ff
      side_bevel_enabled: true
      dot_enabled: true
      comma_enabled: true
      text: ""
      width: 135
      height: 60
      x: 555
      y: 97
      z: 2

  display5:
    - type: segment_display_emulator
      name: display5
      character_count: 7
      character_slant_angle: 5
      character_spacing: 5
      segment_width: 0.1
      segment_interval: .02
      segment_off_color: 4b4c4a30
      segment_on_color: ffa500ff
      side_bevel_enabled: true
      dot_enabled: true
      comma_enabled: true
      text: ""
      width: 140
      height: 60
      x: 562
      y: 258
      z: 2


