#config_version=6
mode:
  start_events: reset_complete
  events_when_started: displays_init_done
  priority: 5
  game_mode: false

segment_display_player:
  player_added{num==1}:
    display1:
      text: "{players[0].score:d}"
      key: scores
      color: black
    display2:
      text: ""
      key: scores
      color: black
    display3:
      text: ""
      key: scores
      color: black
    display4:
      text: ""
      key: scores
      color: black
  player_added{num==2}:
    display2:
      text: "{players[1].score:d}"
      key: scores
      color: black
  player_added{num==3}:
    display3:
      text: "{players[2].score:d}"
      key: scores
      color: black
  player_added{num==4}:
    display4:
      text: "{players[3].score:d}"
      key: scores
      color: black
  game_ended:
    display1:
      action: remove
      key: scores
    display2:
      action: remove
      key: scores
    display3:
      action: remove
      key: scores
    display4:
      action: remove
      key: scores
  player_score{player_num==1}:
    display1:
      text: "{players[0].score:d}"
      key: scores
      color: black
      #priority: 100
  player_score{player_num==2}:
    display2:
      text: "{players[1].score:d}"
      key: scores
      color: black
      #priority: 100
  player_score{player_num==3}:
    display3:
      text: "{players[2].score:d}"
      key: scores
      color: black
      #priority: 100
  player_score{player_num==4}:
    display4:
      text: "{players[3].score:d}"
      key: scores
      color: black
      #priority: 100