#config_version=6
mode:
  start_events: reset_complete
  events_when_started: displays_init_done
  priority: 5
  game_mode: false

widgets:
  backglass:
    - type: image
      image: VolcanoBackglass
      z: 1
  display1:
    - type: segment_display_emulator
      name: display1
      display_type: 7seg
      character_count: 6
      padding: 0
      character_spacing: 15
      segment_width: 0.1
      segment_interval: .02
      segment_off_color: ffffffff
      segment_on_color: 000000ff
      side_bevel_enabled: false
      background_color: ffffffff
      dot_enabled: false
      comma_enabled: false
      text: "111111"
      width: 150
      height: 22
      x: 245
      y: 368
      z: 200
  display2:
    - type: segment_display_emulator
      name: display2
      display_type: 7seg
      character_count: 6
      padding: 0
      character_spacing: 15
      segment_width: 0.1
      segment_interval: .02
      segment_off_color: ffffffff
      segment_on_color: 000000ff
      side_bevel_enabled: false
      background_color: ffffffff
      dot_enabled: false
      comma_enabled: false
      text: "222222"
      width: 150
      height: 22
      x: 555
      y: 368
      z: 200
  display3:
    - type: segment_display_emulator
      name: display3
      display_type: 7seg
      character_count: 6
      padding: 0
      character_spacing: 15
      segment_width: 0.1
      segment_interval: .02
      segment_off_color: ffffffff
      segment_on_color: 000000ff
      side_bevel_enabled: false
      background_color: ffffffff
      dot_enabled: false
      comma_enabled: false
      text: "333333"
      width: 150
      height: 22
      x: 245
      y: 98
      z: 200
  display4:
    - type: segment_display_emulator
      name: display4
      display_type: 7seg
      character_count: 6
      padding: 0
      character_spacing: 15
      segment_width: 0.1
      segment_interval: .02
      segment_off_color: ffffffff
      segment_on_color: 000000ff
      side_bevel_enabled: false
      background_color: ffffffff
      dot_enabled: false
      comma_enabled: false
      text: "444444"
      width: 150
      height: 22
      x: 553
      y: 99
      z: 200
  display5:
    - type: segment_display_emulator
      name: display5
      display_type: 7seg
      character_count: 4
      padding: 0
      character_spacing: 1
      segment_width: 0.1
      segment_interval: .02
      segment_off_color: ffffffff
      segment_on_color: 000000ff
      side_bevel_enabled: false
      background_color: ffffffff
      dot_enabled: false
      comma_enabled: false
      text: "5555"
      width: 12
      height: 12
      x: 422.5
      y: 262.5
      z: 200

slide_player:
  displays_init_done: screen_segement_display

widget_player:
  displays_init_done:
    backglass:
      slide: screen_segement_display
      priority: 10
    display1:
      slide: screen_segement_display
      priority: 10
    display2:
      slide: screen_segement_display
      priority: 10
    display3:
      slide: screen_segement_display
      priority: 10
    display4:
      slide: screen_segement_display
      priority: 10
    display5:
      slide: screen_segement_display
      priority: 10

segment_display_player:
  player_added{num==1}:
    display1:
      text: "{players[0].score:d}"
      key: scores
      color: black
    display2:
      text: ""
      key: scores
      color: black
    display3:
      text: ""
      key: scores
      color: black
    display4:
      text: ""
      key: scores
      color: black
  player_added{num==2}:
    display2:
      text: "{players[1].score:d}"
      key: scores
      color: black
  player_added{num==3}:
    display3:
      text: "{players[2].score:d}"
      key: scores
      color: black
  player_added{num==4}:
    display4:
      text: "{players[3].score:d}"
      key: scores
      color: black

  game_ended:
    display1:
      action: remove
      key: scores
    display2:
      action: remove
      key: scores
    display3:
      action: remove
      key: scores
    display4:
      action: remove
      key: scores

  player_score{player_num==1}:
    display1:
      text: "{players[0].score:d}"
      key: scores
      color: black
      #priority: 100
  player_score{player_num==2}:
    display2:
      text: "{players[1].score:d}"
      key: scores
      color: black
      #priority: 100
  player_score{player_num==3}:
    display3:
      text: "{players[2].score:d}"
      key: scores
      color: black
      #priority: 100
  player_score{player_num==4}:
    display4:
      text: "{players[3].score:d}"
      key: scores
      color: black
      #priority: 100