#config_version=6

mode:
  start_events: ball_started
  priority: 100

shots:
  pop_upper:
    switch: s_pop_upper
  pop_mid:
    switch: s_pop_mid
  pop_lower_left:
    switch: s_pop_lower_left
  pop_lower_right:
    switch: s_pop_lower_right

variable_player:
  pop_upper_hit:
    score: 1000
  pop_mid_hit:
    score: 1000
  pop_lower_left_hit:
    score: 100
  pop_lower_right_hit:
    score: 100


